module.exports = {

  /* Empty Lines */
  "rule-empty-line-before": [true, { except: ["first-nested"] }],
  "custom-properties-empty-line-before": false,
  "dollar-variable-empty-line-before": false,
  "at-rule-empty-line-before": [true, { except: ["blockless-after-blockless", "first-nested"] }],
  "declaration-empty-line-before": [true, { except: ["after-declaration", "first-nested"] }],
  "comment-empty-line-before": true,

  /* Unspecified Placement */
  "unspecified-properties-position": "bottom",

  /* General Order */
  "order": [
    "custom-properties",
    "dollar-variables",
    {
      "type": "at-rule",
      "name": "mixin",
      "hasBlock": false,
    },
    "declarations",
    "at-rules",
    "rules"
  ],

  /* Specific Order */
  "properties-order": [
    {
      "properties": [
        "position",
        "display",
        "content",
        "top",
        "left",
        "right",
        "bottom",
        "margin",
        "margin-top",
        "margin-left",
        "margin-right",
        "margin-bottom",
        "padding",
        "padding-top",
        "padding-left",
        "padding-right",
        "padding-bottom",
        "visibility",
        "width",
        "min-width",
        "max-width",
        "height",
        "min-height",
        "max-height",
        "line-height",
        "appearance",
        "float",
        "clear",
        "z-index",
        "quotes",
        "flex",
        "flex-flow",
        "flex-direction",
        "flex-order",
        "flex-pack",
        "flex-align",
        "table-layout",
        "caption-side",
        "empty-cells",
        "list-style",
        "list-style-position",
        "list-style-type",
        "list-style-image",
        "color",
        "caret-color",
        "font",
        "font-weight",
        "font-style",
        "font-variant",
        "font-size-adjust",
        "font-stretch",
        "font-size",
        "font-family",
        "text-align",
        "text-align-last",
        "text-decoration",
        "text-emphasis",
        "text-emphasis-position",
        "text-emphasis-style",
        "text-emphasis-color",
        "text-indent",
        "text-justify",
        "text-outline",
        "text-transform",
        "text-wrap",
        "text-overflow",
        "text-overflow-ellipsis",
        "text-overflow-mode",
        "text-shadow",
        "counter-increment",
        "counter-reset",
        "tab-size",
        "hyphens",
        "white-space",
        "vertical-align",
        "letter-spacing",
        "word-spacing",
        "word-wrap",
        "word-break",
        "opacity",
        "overflow",
        "overflow-x",
        "overflow-y",
        "src",
        "filter",
        "resize",
        "cursor",
        "nav-index",
        "nav-up",
        "nav-right",
        "nav-down",
        "nav-left",
        "clip",
        "outline",
        "outline-width",
        "outline-style",
        "outline-color",
        "outline-offset",
        "border",
        "border-spacing",
        "border-collapse",
        "border-width",
        "border-style",
        "border-color",
        "border-top",
        "border-top-width",
        "border-top-style",
        "border-top-color",
        "border-right",
        "border-right-width",
        "border-right-style",
        "border-right-color",
        "border-bottom",
        "border-bottom-width",
        "border-bottom-style",
        "border-bottom-color",
        "border-left",
        "border-left-width",
        "border-left-style",
        "border-left-color",
        "border-radius",
        "border-top-left-radius",
        "border-top-right-radius",
        "border-bottom-right-radius",
        "border-bottom-left-radius",
        "border-image",
        "border-image-source",
        "border-image-slice",
        "border-image-width",
        "border-image-outset",
        "border-image-repeat",
        "border-top-image",
        "border-right-image",
        "border-bottom-image",
        "border-left-image",
        "border-corner-image",
        "border-top-left-image",
        "border-top-right-image",
        "border-bottom-right-image",
        "border-bottom-left-image",
        "background",
        "background-color",
        "background-image",
        "background-attachment",
        "background-position",
        "background-position-x",
        "background-position-y",
        "background-clip",
        "background-origin",
        "background-size",
        "background-repeat",
      ]
    },
    {
      "properties": [
        "box-sizing",
        "box-shadow",
        "box-decoration-break",
        "pointer-events",
        "transition",
        "transition-delay",
        "transition-timing-function",
        "transition-duration",
        "transition-property",
        "transform",
        "transform-origin",
        "animation",
        "animation-name",
        "animation-duration",
        "animation-play-state",
        "animation-timing-function",
        "animation-delay",
        "animation-iteration-count",
        "animation-direction",
        "unicode-bidi",
        "direction",
        "columns",
        "column-span",
        "column-width",
        "column-count",
        "column-fill",
        "column-gap",
        "column-rule",
        "column-rule-width",
        "column-rule-style",
        "column-rule-color",
        "break-before",
        "break-inside",
        "break-after",
        "page-break-before",
        "page-break-inside",
        "page-break-after",
        "orphans",
        "widows",
        "zoom",
        "max-zoom",
        "min-zoom",
        "user-zoom",
        "orientation"
      ]
    }
  ],
}